[package]
name = "clawkson-api"
version.workspace = true
edition.workspace = true

[dependencies]
clawkson-core = { path = "../core" }
clawkson-container = { path = "../container" }
clawkson-db = { path = "../db" }
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
reqwest.workspace = true
futures.workspace = true
tokio-stream.workspace = true
tokio-util = "0.7"
async-stream = "0.3"
async-trait = "0.1"
denkwerk = { path = "../../../denkwerk" }
argon2.workspace = true
rand.workspace = true
hex = "0.4"
pdf-extract = "0.7"
aws-sdk-s3.workspace = true
aws-config.workspace = true
aws-types.workspace = true
base64 = "0.22"
tempfile = "3"
glob-match = "0.2"
url = "2"
cron = "0.12"
